### ISSUE TITLE
Bug in the looping character batches

### ISSUE THREAD

**Issue by Henry-E** [thomasZen/stateful_lstm_keras_text_generation#1]
https://github.com/thomasZen/stateful_lstm_keras_text_generation/blob/master/stateful_lstm_text_generation.py#L120

You loop over range(BATCH_SIZE) but what you actually need to do is loop over some value linked with the number of characters in a sentence. The original example used a max length of 40, what you're doing here is essentially setting a max length of 128 and ignoring everything comes after. This might explain why in my own experiments with your code it never converged to anything meaningful on the Nietzche dataset.

**Comment by Henry-E** [comment]
After testing out the original code yours runs about 5 - 8 times faster! It would be great if you could add some more comments to help understand what you changed and why. In the meantime I'll probably be trying to figure out how to adapt it or fix it because the original lstm text generation code is way too slow for the size of dataset that I'm using.

**Comment by thomasZen** [comment]
Sorry for the late response. 

First of all notice that I only do backpropagation through time for one time step:
`X = np.zeros((BATCH_SIZE, 1, len(char_indices)), dtype=np.bool)`
That should be the main reason for the speed improvement.

The implementation of the sentence generation is a bit tricky. Batch_size (128) sentences are processed in parallel. If all characters of the sentence are processed for a specific batch, the sentence_generator yields a new sentence.

Also notice that the hidden state of the network never gets reset, as this is an example for a stateful lstm. So in principal the network should learn to forget the information stored in the hidden state, once a new sentence is started (since the sentences are not generated in order).
